apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-mysql
  labels:
    app: mall-mysql
    version: v1
spec:
  selector:
    matchLabels:
      app: mall-mysql
  template:
    metadata:
      labels:
        app: mall-mysql
        version: v1
    spec:
      containers:
        - image: mysql:5.7
          name: mall-mysql
          env:
            # Use secret in real usage
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
              name: mysql-3306

---

apiVersion: v1
kind: Service
metadata:
  name: mall-mysql
  labels:
    app: mall-mysql
spec:
  ports:
    - nodePort: 30066
      port: 3306
      protocol: TCP
      targetPort: 3306
      name: mysql-3306
  selector:
    app: mall-mysql
  type: NodePort
