apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-search
  labels:
    app: mall-search
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-search
  template:
    metadata:
      labels:
        app: mall-search
        version: v1
    spec:
      containers:
        - name: mall-search
          # 指定Docker Hub中的镜像地址
          image: registry.cn-shenzhen.aliyuncs.com/k8small/mall-search:1.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            # 指定环境
            - name: spring.profiles.active
              value: prod
            # 指定时区
            - name: TZ
              value: Asia/Shanghai
            - name: spring_datasource_url
              value: jdbc:mysql://mall-mysql:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
            - name: spring_elasticsearch_rest_uris
              value: elasticsearch:9200

---

apiVersion: v1
kind: Service
metadata:
  name: mall-search
  labels:
    app: mall-search
spec:
  type: ClusterIP
  selector:
    app: mall-search
  ports:
    - name: http
      protocol: TCP
      port: 8081
      targetPort: 8081