apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-gateway
  labels:
    app: mall-gateway
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-gateway
  template:
    metadata:
      labels:
        app: mall-gateway
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: mall-gateway
          # 指定Docker Hub中的镜像地址
          image: registry.cn-shenzhen.aliyuncs.com/k8small/mall-gateway:1.0-eureka
          imagePullPolicy: Always
          ports:
            - containerPort: 8201
          env:
            # 指定环境
            - name: spring.profiles.active
              value: prod
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            # 指定时区
            - name: TZ
              value: Asia/Shanghai
            - name: spring_redis_host
              value: redis.${NAMESPACE}
            - name: eureka_client_serviceUrl_defaultZone
              value: http://eureka.${NAMESPACE}:8761/eureka


---

apiVersion: v1
kind: Service
metadata:
  name: mall-gateway
  labels:
    app: mall-gateway
spec:
  type: NodePort
  selector:
    app: mall-gateway
  ports:
    - name: http
      protocol: TCP
      port: 8201
      targetPort: 8201
      nodePort: 30201