apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-admin
  labels:
    app: mall-admin
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-admin
  template:
    metadata:
      labels:
        app: mall-admin
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: mall-admin
          # 指定Docker Hub中的镜像地址
          image: registry.cn-shenzhen.aliyuncs.com/k8small/mall-admin:1.0-eureka
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # 指定环境
            - name: spring.profiles.active
              value: prod
            # 指定时区
            - name: TZ
              value: Asia/Shanghai
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: spring_datasource_url
              value: jdbc:mysql://mall-mysql.${NAMESPACE}:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
            - name: spring_redis_host
              value: redis.${NAMESPACE}
            - name: spring_rabbitmq_host
              value: rabbitmq.${NAMESPACE}
            - name: spring_rabbitmq_username
              value: guest
            - name: spring_rabbitmq_password
              value: guest
            - name: eureka_client_serviceUrl_defaultZone
              value: http://eureka.${NAMESPACE}:8761/eureka
---

apiVersion: v1
kind: Service
metadata:
  name: mall-admin
  labels:
    app: mall-admin
spec:
  type: ClusterIP
  selector:
    app: mall-admin
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080