apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-auth
  labels:
    app: mall-auth
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-auth
  template:
    metadata:
      labels:
        app: mall-auth
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: mall-auth
          # 指定Docker Hub中的镜像地址
          image: registry.cn-shenzhen.aliyuncs.com/k8small/mall-auth:1.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8401
          env:
            # 指定环境
            - name: spring.profiles.active
              value: prod
            # 指定时区
            - name: TZ
              value: Asia/Shanghai

---

apiVersion: v1
kind: Service
metadata:
  name: mall-auth
  labels:
    app: mall-auth
spec:
  type: ClusterIP
  selector:
    app: mall-auth
  ports:
    - name: http
      protocol: TCP
      port: 8401
      targetPort: 8401