apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-admin
  namespace: mall
  labels:
    app: mall-admin
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-admin
  template:
    metadata:
      labels:
        app: mall-admin
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: mall-admin
          # 指定Docker Hub中的镜像地址
          image: harbor.cloud2go.cn/macrodocker/mall-admin:1.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # 指定环境
            - name: spring.profiles.active
              value: prod
            # 指定时区
            - name: TZ
              value: Asia/Shanghai
            - name: spring_datasource_url
              value: jdbc:mysql://mall-mysql:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
            - name: spring_elasticsearch_rest_uris
              value: elasticsearch:9200
            - name: spring_redis_host
              value: redis
            - name: spring_rabbitmq_host
              value: rabbitmq
            - name: spring_rabbitmq_username
              value: guest
            - name: spring_rabbitmq_password
              value: guest
---

apiVersion: v1
kind: Service
metadata:
  name: mall-admin
  namespace: mall
  labels:
    app: mall-admin
spec:
  type: ClusterIP
  selector:
    app: mall-admin
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080