apiVersion: apps/v1
kind: Deployment
metadata:
  name: mall-admin-web
  namespace: mall
  labels:
    app: mall-admin-web
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-admin-web
  template:
    metadata:
      labels:
        app: mall-admin-web
        version: v1
    spec:
      restartPolicy: Always
      containers:
        - name: mall-admin-web
          # 指定Docker Hub中的镜像地址
          image: harbor.cloud2go.cn/macrodocker/mall-admin-web:1.0-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: mall-admin-web
  namespace: mall
  labels:
    app: mall-admin-web
spec:
  type: NodePort
  selector:
    app: mall-admin-web
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080